/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 10-окт.-2022 20:47:28 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Basket` CASCADE
;

DROP TABLE IF EXISTS `Order` CASCADE
;

DROP TABLE IF EXISTS `Product` CASCADE
;

DROP TABLE IF EXISTS `Properties` CASCADE
;

DROP TABLE IF EXISTS `User` CASCADE
;

/* Create Tables */

CREATE TABLE `Basket`
(
	`Total_price` DOUBLE(10,2) NULL,
	`BasketID` INT NOT NULL,
	`OrderID` INT NOT NULL,
	CONSTRAINT `PK_Basket` PRIMARY KEY (`BasketID` ASC)
)

;

CREATE TABLE `Order`
(
	`Adress` VARCHAR(50) NULL,
	`Date` DATE NULL,
	`Status` VARCHAR(50) NULL,
	`OrderID` INT NOT NULL,
	`UserID` INT NULL,
	CONSTRAINT `PK_Order` PRIMARY KEY (`OrderID` ASC)
)

;

CREATE TABLE `Product`
(
	`Code` INT NULL,
	`Image_url` VARCHAR(50) NULL,
	`Is_in_basket` BOOL NULL,
	`Name` VARCHAR(50) NULL,
	`Price` DOUBLE(10,2) NULL,
	`Type` VARCHAR(50) NULL,
	`ProductID` INT NOT NULL,
	`BasketID` INT NULL,
	`PropertiesID` INT NOT NULL,
	CONSTRAINT `PK_Product` PRIMARY KEY (`ProductID` ASC)
)

;

CREATE TABLE `Properties`
(
	`Color` VARCHAR(50) NULL,
	`Material` VARCHAR(50) NULL,
	`Producer` VARCHAR(50) NULL,
	`Size` VARCHAR(50) NULL,
	`Style` VARCHAR(50) NULL,
	`PropertiesID` INT NOT NULL,
	CONSTRAINT `PK_Properties` PRIMARY KEY (`PropertiesID` ASC)
)

;

CREATE TABLE `User`
(
	`E-mail` VARCHAR(50) NULL,
	`Login` VARCHAR(50) NULL,
	`Name` VARCHAR(50) NULL,
	`Password` VARCHAR(50) NULL,
	`Surname` VARCHAR(50) NULL,
	`Type` VARCHAR(50) NULL,
	`UserID` INT NOT NULL,
	CONSTRAINT `PK_User` PRIMARY KEY (`UserID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Basket` 
 ADD CONSTRAINT `FK_Basket_Order`
	FOREIGN KEY (`OrderID`) REFERENCES `Order` (`OrderID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Order` 
 ADD CONSTRAINT `FK_Order_User`
	FOREIGN KEY (`UserID`) REFERENCES `User` (`UserID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Product` 
 ADD CONSTRAINT `FK_Product_Basket`
	FOREIGN KEY (`BasketID`) REFERENCES `Basket` (`BasketID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Product` 
 ADD CONSTRAINT `FK_Product_Properties`
	FOREIGN KEY (`PropertiesID`) REFERENCES `Properties` (`PropertiesID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
